openapi: 3.0.0
info:
  title: Optibus Operations Driver Absences Preferences API
  version: 2.8.17
  description: '**Welcome to the Optibus Operations API documentation!**


    Optibus Operations is a cloud-based software solution that enables public transport providers to optimize their operations, planning, and scheduling. Our API provides programmatic access to Optibus Operations'' functionality, allowing you to integrate it with your own applications and systems.



    '
  license:
    name: Optibus Ltd, All rights reserved
  contact: {}
servers:
- url: https://YOUR-OPTIBUS-ACCOUNT.api.ops.optibus.co
  description: Contact your Optibus Customer Success Manager for the actual baseURL and API credentials to use.
tags:
- name: Preferences
paths:
  /v1/preferences/holidays:
    get:
      operationId: GetHolidays
      responses:
        '200':
          description: Holiday preferences
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPreferencesHolidaysResponse'
      description: 'Returns the configured holidays (as in bank holidays).

        This is distinct from individual driver absences.

        If `startDate` and `endDate` are provided, the response will include only holidays within that date range.

        If neither is provided, all configured holidays are returned.


        ### Important Notes:

        - Both `startDate` and `endDate` must be provided together.

        - Dates are expected in the format `YYYY-MM-DD`.'
      summary: List holidays
      tags:
      - Preferences
      security:
      - api_key: []
      parameters: []
  /v1/preferences/absence-types:
    get:
      operationId: GetAbsenceTypes
      responses:
        '200':
          description: Absence types
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPreferencesAbsenceTypesResponse'
      description: Returns the configured absence types.
      summary: List absence types
      tags:
      - Preferences
      security:
      - api_key: []
      parameters: []
components:
  schemas:
    PreferenceDateRange:
      properties:
        to:
          $ref: '#/components/schemas/StringifyDate'
        from:
          $ref: '#/components/schemas/StringifyDate'
      required:
      - to
      - from
      type: object
    HolidayInfo:
      properties:
        groupName:
          type: string
          description: Grouping category for the holiday, e.g., "New Year", this is the name that will be displayed in the UI.
        name:
          type: string
          description: The name of the holiday, e.g., "New Year 2012".
        timeDefinition:
          $ref: '#/components/schemas/PreferenceDateRange'
          description: The date range that defines the holiday period.
      required:
      - name
      - timeDefinition
      type: object
    StringifyDate:
      type: string
      format: date
      description: Stringified ISO8601 date in the form of `YYYY-MM-dd`, for example `2017-07-21`
    AbsenceType:
      properties:
        name:
          type: string
        code:
          type: string
      required:
      - name
      - code
      type: object
    GetPreferencesAbsenceTypesResponse:
      properties:
        absenceTypes:
          items:
            $ref: '#/components/schemas/AbsenceType'
          type: array
      required:
      - absenceTypes
      type: object
    GetPreferencesHolidaysResponse:
      items:
        $ref: '#/components/schemas/HolidayInfo'
      type: array
  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header
x-tagGroups:
- name: General API Info
  tags:
  - Authentication
  - Versioning
- name: Use case guides
  tags:
  - HR System Integration Guides
  - Fleet Management System Integration Guides
  - Operational Plan Query Guides
  - Custom Driver App Notification Action Guide
- name: Client preferences
  tags:
  - Preferences
- name: Resource Management
  tags:
  - Regions
  - Drivers
  - Driver Absences
  - Driver Employment Periods
  - Driver Custom Attributes
  - Driver Groups
  - Vehicles
  - Vehicle Downtimes
  - Vehicle Custom Attributes
- name: Operations Management
  tags:
  - Roster
  - Operational Plan
  - Tasks
  - Stops
  - Signing Times
- name: Work & Payroll
  tags:
  - Work Entities
  - Payroll
  - Statistics
- name: Private Hires
  tags:
  - Private Hires
- name: Driver App Integration
  tags:
  - Driver App Notifications
- name: Event Webhooks
  tags:
  - Event Webhooks
- name: Data Ingestion
  tags:
  - Tacho Ingestion
- name: Deprecated API Endpoints
  tags:
  - Drivers (Deprecated)
  - Vehicles (Deprecated)
  - Operational Plan (Deprecated)
- name: Changelog
  tags:
  - Changelog
